### ISSUE TITLE
 Krone BiGPack 1290 HDP II baler with BaleCollect ejects bales individually instead of in sets of three.

### ISSUE THREAD

**Issue by MeRida2104** [Timmeey86/FS25_UnloadBalesEarly#4] opened 2024-03-22 08:22 UTC
Hi Dude,

the Krone BiGPack 1290 HDP II baler with BaleCollect from the Straw Harvest Pack (https://www.farming-simulator.com/mod.php?lang=de&country=at&mod_id=277447) no longer collects the bales in sets of three, but instead directly ejects them. 

Without UnloadBalesEarly it works well.

Could you take a look of this?

Best regards
MeRida

**Comment by Timmeey86** [comment] 2024-03-22 19:52
This is a keybinding conflict. It should work if you assign "SH: Toggle collect mode" to a different key than O in the keybindings

**Comment by MeRida2104** [comment] 2024-03-22 20:43
I don't press any key combinations. Once UnloadBalesEarly is activated, each bale will be unloaded individually.

**Comment by Timmeey86** [comment] 2024-03-22 20:51
I did a test with about 10 mods including straw harvest and could not reproduce the issue.
However, by default, the button O would change the configuration of the bale collector, and one of those configurations unloads bales directly. After assigning that straw harvest keybinding to a different button (you can't change the UnloadBalesEarly one yet), I saw the F1 entry which displays the current configuration of the bale collector and allows you to cycle through them

**Comment by MeRida2104** [comment] 2024-03-22 21:46
Thank you for the detailed explanation. I will test it more thoroughly again.

**Comment by FirenzeIT** [comment] 2024-04-08 20:00
> Thank you for the detailed explanation. I will test it more thoroughly again.

Hi, I suggest you make a video clip that captures the whole process, so at least it is easier for the author to fix the bug/problem

**Comment by Timmeey86** [comment] 2024-04-10 19:17
> > Thank you for the detailed explanation. I will test it more thoroughly again.
> 
> Hi, I suggest you make a video clip that captures the whole process, so at least it is easier for the author to fix the bug/problem

I believe this was just a misunderstanding, I will close the issue

**Closed as completed by Timmeey86** 2024-04-10 19:17 UTC

**Comment by FirenzeIT** [comment] 2024-04-10 19:21
Ok, the new and last update it's available on modhub, thank you for your work @Timmeey86
